version: '3'
services:
  app:
    build: .
    image: airbyte-automation:latest
    environment:
      AIRBYTE_ENDPOINT: http://host.docker.internal:8006
      AIRBYTE_BASIC_AUTH: "false"
      AIRBYTE_USERNAME: airbyte
      AIRBYTE_PASSWORD: password
      DB_PORT: 5432
      DB_NAME: decidim
      WORKSPACE_UUID: 63c43ced-d578-421a-9d38-7a319035e139
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ~/.kube/config:/.kube/config
